services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data  

  nginx:
    image: nginx:latest
    ports:
    - "5002:5002"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
    - web

volumes:
  redis-data: